## SITUAÇÃO 2: PREVISÃO SE O ESTUDANTE VAI REPROVAR...

## IMPORTANDO ARQUIVO TRATADO:

In [1]:
#Importando bibliotecas
import pandas as pd
df_tratado = pd.read_csv('data/arquivo_tratado.csv', sep=',')

In [2]:
df_tratado.info()

<class 'pandas.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   idade                395 non-null    int64
 1   tempo_viagem_escola  395 non-null    int64
 2   hora_de_estudar      395 non-null    int64
 3   internet             395 non-null    int64
 4   estado_saude_atual   395 non-null    int64
 5   n_faltas_escolares   395 non-null    int64
 6   nota1                395 non-null    int64
 7   nota2                395 non-null    int64
 8   nota3                395 non-null    int64
 9   genero               395 non-null    int64
 10  reprovacao           395 non-null    int64
dtypes: int64(11)
memory usage: 34.1 KB

## SEPARAÇÃO DOS DADOS PARA TREINAMENTO E TESTE DOS MODELOS:

In [3]:
from sklearn.model_selection import train_test_split

#Separando a base de treino de X e y
X=df_tratado.drop(['reprovacao'],axis=1)
y=df_tratado['reprovacao']

X_treino,X_teste,y_treino,y_teste=train_test_split(
    X,
    y,
    test_size=0.33,
    random_state=42
)

In [4]:
lista_parametros_classificacao=[]
lista_parametros_regressao=[]
dict_llm_classificacao={}
dict_llm_regressao={}

## MODELOS DE LLMs:

## Modelos de Classificação:

In [5]:
from sklearn import tree

classifica_arv=tree.DecisionTreeClassifier(random_state=42)
classifica_arv=classifica_arv.fit(X_treino,y_treino)
y_pred_arv=classifica_arv.predict(X_teste)

In [6]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

dict_llm_classificacao['nome']='DecisionTreeClassifier'
accuracy_arv = accuracy_score(y_teste, y_pred_arv)
dict_llm_classificacao['acuracia']=accuracy_arv
print(f'acuracia: {accuracy_arv:.2f}')
precision_arv= precision_score(y_teste, y_pred_arv,average='weighted')
dict_llm_classificacao['precisao']=precision_arv
print(f'precisao: {precision_arv:.2f}')
recall_arv = recall_score(y_teste, y_pred_arv,average='weighted')
dict_llm_classificacao['recall']=recall_arv
print(f'recall: {recall_arv:.2f}')
lista_parametros_classificacao.append(dict_llm_classificacao.copy())
dict_llm_classificacao.clear()

acuracia: 0.73
precisao: 0.77
recall: 0.73

In [7]:
from sklearn.neighbors import KNeighborsClassifier

classifica_kne=KNeighborsClassifier(n_neighbors=3)
classifica_kne=classifica_kne.fit(X_treino,y_treino)
y_pred_kne=classifica_kne.predict(X_teste)

In [8]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

dict_llm_classificacao['nome']='KNeighborsClassifier'
accuracy_kne = accuracy_score(y_teste, y_pred_kne)
dict_llm_classificacao['acuracia']=accuracy_kne
print(f'acuracia: {accuracy_kne:.2f}')
precision_kne= precision_score(y_teste, y_pred_kne,average='weighted')
dict_llm_classificacao['precisao']=precision_kne
print(f'precisao: {precision_kne:.2f}')
recall_kne = recall_score(y_teste, y_pred_kne,average='weighted')
dict_llm_classificacao['recall']=recall_kne
print(f'recall: {recall_kne:.2f}')
lista_parametros_classificacao.append(dict_llm_classificacao.copy())
dict_llm_classificacao.clear()

acuracia: 0.79
precisao: 0.77
recall: 0.79

In [9]:
from sklearn.linear_model import LogisticRegression

classifica_log=LogisticRegression(random_state=42)
classifica_log=classifica_log.fit(X_treino,y_treino)
y_pred_log=classifica_log.predict(X_teste)

C:\Users\Win10pro\PycharmProjects\AnaliseEducacional\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [10]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

dict_llm_classificacao['nome']='KNeighborsClassifier'
accuracy_log = accuracy_score(y_teste, y_pred_log)
dict_llm_classificacao['acuracia']=accuracy_log
print(f'acuracia: {accuracy_log:.2f}')
precision_log= precision_score(y_teste, y_pred_log,average='weighted')
dict_llm_classificacao['precisao']=precision_log
print(f'precisao: {precision_log:.2f}')
recall_log = recall_score(y_teste, y_pred_log,average='weighted')
dict_llm_classificacao['recall']=recall_log
print(f'recall: {recall_log:.2f}')
lista_parametros_classificacao.append(dict_llm_classificacao.copy())
dict_llm_classificacao.clear()

acuracia: 0.84
precisao: 0.83
recall: 0.84

## Modelos de Regressão:

In [11]:
from sklearn.linear_model import LinearRegression

classifica_lir=LinearRegression()
classifica_lir=LinearRegression().fit(X_treino,y_treino)
y_pred_lir=classifica_lir.predict(X_teste)

In [12]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
import numpy as np

dict_llm_regressao['nome']='LinearRegression'
r2_lir = r2_score(y_teste, y_pred_lir)
dict_llm_regressao['R2']=r2_lir
print(f'R2: {r2_lir:.2f}')
mae_lir= mean_absolute_error(y_teste, y_pred_lir)
dict_llm_regressao['MAE']=mae_lir
print(f'MAE: {mae_lir:.2f}')
rmse_lir = np.sqrt(mean_squared_error(y_teste, y_pred_lir))
dict_llm_regressao['RMSE']=rmse_lir
print(f'RMSE: {rmse_lir:.2f}')
lista_parametros_regressao.append(dict_llm_regressao.copy())

R2: 0.24
MAE: 0.27
RMSE: 0.34

In [13]:
from sklearn.ensemble import RandomForestRegressor

classifica_rfr=RandomForestRegressor()
classifica_rfr=classifica_rfr.fit(X_treino,y_treino)
y_pred_rfr=classifica_rfr.predict(X_teste)

In [14]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
import numpy as np

dict_llm_regressao['nome']='RandomForestRegressor'
r2_rfr = r2_score(y_teste, y_pred_rfr)
dict_llm_regressao['R2']=r2_rfr
print(f'R2: {r2_rfr:.2f}')
mae_rfr= mean_absolute_error(y_teste, y_pred_rfr)
dict_llm_regressao['MAE']=mae_rfr
print(f'MAE: {mae_rfr:.2f}')
rmse_rfr = np.sqrt(mean_squared_error(y_teste, y_pred_rfr))
dict_llm_regressao['RMSE']=rmse_rfr
print(f'RMSE: {rmse_rfr:.2f}')
lista_parametros_regressao.append(dict_llm_regressao.copy())

R2: 0.22
MAE: 0.24
RMSE: 0.35

In [15]:
from sklearn.ensemble import HistGradientBoostingRegressor

classifica_hgbr=HistGradientBoostingRegressor()
classifica_hgbr=classifica_hgbr.fit(X_treino,y_treino)
y_pred_hgbr=classifica_hgbr.predict(X_teste)

C:\Users\Win10pro\PycharmProjects\AnaliseEducacional\.venv\Lib\site-packages\joblib\externals\loky\backend\context.py:131: UserWarning: Could not find the number of physical cores for the following reason:
found 0 physical cores < 1
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Users\Win10pro\PycharmProjects\AnaliseEducacional\.venv\Lib\site-packages\joblib\externals\loky\backend\context.py", line 255, in _count_physical_cores
    raise ValueError(f"found {cpu_count_physical} physical cores < 1")

In [16]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
import numpy as np

dict_llm_regressao['nome']='HistGradientBoostingRegressor'
r2_hgbr = r2_score(y_teste, y_pred_hgbr)
dict_llm_regressao['R2']=r2_hgbr
print(f'R2: {r2_hgbr:.2f}')
mae_hgbr= mean_absolute_error(y_teste, y_pred_hgbr)
dict_llm_regressao['MAE']=mae_hgbr
print(f'MAE: {mae_hgbr:.2f}')
rmse_hgbr = np.sqrt(mean_squared_error(y_teste, y_pred_hgbr))
dict_llm_regressao['RMSE']=rmse_hgbr
print(f'RMSE: {rmse_hgbr:.2f}')
lista_parametros_regressao.append(dict_llm_regressao.copy())

R2: 0.21
MAE: 0.24
RMSE: 0.35

In [17]:
import pandas as pd
df_regressao=pd.DataFrame(lista_parametros_regressao)
print(display(df_regressao))

                            nome        R2       MAE      RMSE
0               LinearRegression  0.242440  0.272198  0.342027
1          RandomForestRegressor  0.223160  0.240687  0.346352
2  HistGradientBoostingRegressor  0.214822  0.241139  0.348205

None

In [18]:
import pandas as pd
df_classificacao=pd.DataFrame(lista_parametros_classificacao)
df_classificacao

                     nome  acuracia  precisao    recall
0  DecisionTreeClassifier  0.725191  0.765017  0.725191
1    KNeighborsClassifier  0.786260  0.773253  0.786260
2    KNeighborsClassifier  0.839695  0.825535  0.839695